server:
  port: 8081
spring:
  dubbo:
    registry:
      address: zookeeper://ming:2181
    application:
      name: accountInfoService
      owner: mingxiangjun
    protocol:
      name: dubbo
      port: 20882
    provider:
      version: 1.0.0
      group: download
    consumer:
      version: 1.0.0
      group: download
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dbtest?useUnicode=true&characterEncoding=utf-8&useSSL=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


