server:
  port: 8082
spring:
  dubbo:
    registry:
      address: zookeeper://ming:2181
    application:
      name: webside
      owner: mingxiangjun
    protocol:
      name: dubbo
      port: 2881
    provider:
      version: 1.0.0
      group: download
    consumer:
      version: 1.0.0
      group: download
  security:
    user:
      name: admin
      password: 123456
      roles:
common:
  defaultPageSize: 20
  batchSizeLimit: 200

management:
  endpoints:
    web:
      base-path: /actuator
  server:
    port: 80
  health:
    diskspace:
      path: D:/spaceInfo.txt
      enabled: true
